### ISSUE TITLE
HW_PROBE

### ISSUE THREAD

**Issue by UweBonnes** [biolds/tibuta-w100#1]
Hello,

thanks for your effort.  I will be gratefull if you enter the W100  device at https://linux-hardware.org/

Cheers

**Comment by biolds** [comment]
Hi,

I've done the probe, it's uploaded there https://linux-hardware.org/?probe=202a9be7b7
Please note that it was done with usb wifi dongle plugged-in, and extra storage.

**Comment by UweBonnes** [comment]
Thanks. Now I know better what to expects.
