### ISSUE TITLE
make kernel for touchscreen fails at the end : errors, disk corruption (read-only)

### ISSUE THREAD

**Issue by LionelHoudelier** [biolds/tibuta-w100#5]
My system:

I just bought a new w100 and installed Debian 12.5 dvd (kernel 6.1.0-18amd64)

I followed many times the touchscreen procedure but same errors at the end (after 5 hours last time) of "make" command : the partition gets "read-only" and the system crashes. Then at reboot i need to do a fsck. It looks like a memory failure...

The touchsreen works although partially, but with bad calibration. It is not mentionned with xinput.

Can i build the kernel on another machine and then import it on the w100?

Here is my postinstall script:

``` 
#!/bin/sh
if [ 1 = 1 ];then
sed -i "/deb cdrom:/ s/^#*/##/" /etc/apt/sources.list
apt update
apt upgrade -y
#for the wifi
sed -i "/GRUB_CMDLINE_LINUX_DEFAULT/ s/^#*/##/" /etc/default/grub
sed -i '/GRUB_CMDLINE_LINUX_DEFAULT/a GRUB_CMDLINE_LINUX_DEFAULT="quiet pcie_port_pm=off"' /etc/default/grub
export PATH="/sbin:/usr/bin:/usr/sbin:$PATH"
tee -a /usr/sbin/grub-update > /dev/null <<EOT
#!/bin/sh
set -e
exec grub-mkconfig -o /boot/grub/grub.cfg "$@"
EOT
chmod +x /usr/sbin/grub-update
grub-update
#to install the firmware
git clone https://github.com/biolds/tibuta-w100.git
#firmmware/silead/
mkdir -p /lib/firmware/silead/
cp tibuta-w100/uploads/Home/gsl1680-tibuta-w100.fw /lib/firmware/silead/
dpkg -i tibuta-w100/uploads/Home/linux-image-6.1.12+_6.1.12+-1_amd64.deb
fi
#reboot
# to rebuild the kernel
apt-get install -y build-essential linux-source-6.1 bc kmod cpio flex libncurses5-dev libelf-dev libssl-dev dwarves bison python3
cd /root
tar xaf /usr/src/linux-source-6.1.tar.xz
cd /root/linux-source-6.1
patch < tibuta-w100/uploads/Home/0001-tibuta-touchpad-module.patch
#
echo "select option 3 to question about zero check safest then ALWAYS ENTER"
sleep 3
make -j8 deb-pkg
```

**Comment by OldManYellsAtCloud** [comment]
> Can i build the kernel on another machine and then import it on the w100?
Sure, that's what I do also. Compile the kernel on a beefier machine, copy the whole build folder, and then run `sudo make install` on the tablet, which is quick. It's an x86_64 based tablet, so on most likely you don't even need to cross compile.

**Comment by LionelHoudelier** [comment]
Would you know why the rebuild package including this missing firmware is not available in this github project?

**Comment by biolds** [comment]
Hi,

There is a patched kernel package available in https://github.com/biolds/tibuta-w100/tree/main/uploads/Home. Debian usually ships firmwares in separate packages (due to licensing reason i guess), so the kernel build does not include them out of the box. I'll see if I can find some time to build/upload an updated kernel.

**Comment by LionelHoudelier** [comment]
Thanks again

**Comment by biolds** [comment]
I have set up an automated build of the kernel on Gitlab, the latest version shoulud always be available at https://gitlab.com/biolds1/tibuta-w100-kernel/-/pipelines?scope=tags&page=1

**Comment by LionelHoudelier** [comment]
> > Can i build the kernel on another machine and then import it on the w100?
> 
> Sure, that's what I do also. Compile the kernel on a beefier machine, copy the whole build folder, and then run `sudo make install` (or whatever your favorite installation command is) on the tablet, which is quick. It's an x86_64 based tablet, so most likely you don't even need to cross compile.

This worked!
This was the solution!

**Comment by LionelHoudelier** [comment]
> I have set up an automated build of the kernel on Gitlab, the latest version shoulud always be available at https://gitlab.com/biolds1/tibuta-w100-kernel/-/pipelines?scope=tags&page=1
Thanks for the community, but
Why should it not be published or mentionned on this github project in the README.MD?
