### ISSUE TITLE
Make touchscreen work with wayland

### ISSUE THREAD

**Issue by LionelHoudelier** [biolds/tibuta-w100#6]
Hi all,
Any idea to make it work with wayland session?
I searched for a long time to calibrate (libinput, udev rule) without success.

**Comment by LionelHoudelier** [comment]
I found the solution! Touchscreen is now working like out of the box in all orientations, in xorg and wayland.
Todo is:
- Check the event number of the device "silead_ts":
`sudo libinput list-devices`
You should find "event18". Remember the number.
- Optional, just to look the changes afterwards:
`sudo udevadm info /dev/input/event18`
and look at the CALIBRATION_MATRIX value.
- Make a new rule for udev:
`text='DRIVERS=="silead_ts" ENV{LIBINPUT_CALIBRATION_MATRIX}="1.32 0 -0.32 0 1.17 -0.17 0 0 1"'`
- Write the rule in file
`echo "$text" | sudo tee /etc/udev/rules.d/99-silead-touch.rules`
- Test the rule to see if the file was accepted with the parameters:
`sudo udevadm test /dev/input/event18`
- Activate the rule
`sudo udevadm trigger /dev/input/event18`

This should work immediately, without reboot.
Enjoy!
I will write a PR.

**Comment by biolds** [comment]
Nice!
